### ISSUE TITLE
Dependency Issues and missing install instructions.

### ISSUE THREAD

**Issue by kyleroberthammond** [tutsplus/modern-web-apps-with-angular-2#1]
You need to change your package.json for the quick start package.json for angular-in-memory-web-api to be 0.1.13 not ~0.1.13 or else it has dependency clashes with rxjs and zone.js.

**Comment by kyleroberthammond** [comment]
For simplicity sake i think it would be best just to lock all the versions. So people who watch the tutioral have a simple setup. Everything seems to be clashing with everything otherwise. E.g problems with TSC not loading and stuff.
Simple way of getting people going.

**Comment by adamarthurryan** [comment]
@kyleroberthammond That makes sense to me. I pushed a commit with the version numbers frozen. 

Does that work for you @andrew8088 ?

**Comment by andrew8088** [comment]
@adamarthurryan @kyleroberthammond Sounds good; thanks!
